name: nwc
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - altair=4.2.2=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - arrow-cpp=8.0.0=py310h38b8b19_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=19.1.0=py_0
  - aws-c-common=0.4.57=ha925a31_1
  - aws-c-event-stream=0.1.6=hd77b12b_5
  - aws-checksums=0.1.9=ha925a31_0
  - aws-sdk-cpp=1.8.185=hd77b12b_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backoff=1.11.1=pyhd8ed1ab_0
  - beautifulsoup4=4.11.2=pyha770c72_0
  - black=22.6.0=py310haa95532_0
  - blas=1.0=mkl
  - bleach=6.0.0=pyhd8ed1ab_0
  - blosc=1.21.3=hdccc3a2_0
  - bokeh=2.4.3=py310haa95532_0
  - boltons=21.0.0=pyhd8ed1ab_0
  - boost-cpp=1.81.0=h92ca6c8_0
  - bottleneck=1.3.5=py310h9128911_0
  - brotli=1.0.9=hcfcfb64_8
  - brotli-bin=1.0.9=hcfcfb64_8
  - brotlipy=0.7.0=py310h2bbff1b_1002
  - bzip2=1.0.8=he774522_0
  - c-ares=1.18.1=h8ffe710_0
  - ca-certificates=2022.12.7=h5b45459_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cartopy=0.21.1=py310h5081e89_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310h2bbff1b_3
  - cfitsio=3.470=h2bbff1b_7
  - cftime=1.6.2=py310h9b08ddd_1
  - chardet=5.1.0=py310h5588dad_0
  - charls=2.2.0=h6c2663c_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.0.4=py310haa95532_0
  - click-spinner=0.1.10=pyh9f0ad1d_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - colorama=0.4.6=py310haa95532_0
  - colorlog=6.7.0=py310h5588dad_1
  - comm=0.1.2=py310haa95532_0
  - contourpy=1.0.7=py310h232114e_0
  - cryptography=38.0.4=py310h21b164f_0
  - curl=7.87.0=h2bbff1b_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.12.0=py310h2bbff1b_0
  - dacite=1.6.0=pyhd3deb0d_0
  - dask=2023.1.1=pyhd8ed1ab_0
  - dask-core=2023.1.1=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - datapane=0.15.6=pyhd8ed1ab_0
  - debugpy=1.5.1=py310hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distributed=2023.1.1=pyhd8ed1ab_0
  - dominate=2.7.0=pyhd8ed1ab_0
  - dulwich=0.20.50=py310h8d17308_0
  - eccodes=2.28.0=h75381da_0
  - eigen=3.4.0=h2d74725_0
  - entrypoints=0.4=py310haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - face=20.1.1=py_0
  - fftw=3.3.10=nompi_h38027f0_106
  - flake8=6.0.0=py310haa95532_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fonttools=4.38.0=py310h8d17308_1
  - freeglut=3.2.2=h0e60522_1
  - freetype=2.12.1=ha860e81_0
  - fsspec=2022.11.0=py310haa95532_0
  - furl=2.1.3=pyhd8ed1ab_0
  - geos=3.11.1=h1537add_0
  - gflags=2.2.2=ha925a31_1004
  - giflib=5.2.1=h8d14728_2
  - glib=2.69.1=h5dc1a3c_2
  - glog=0.6.0=h4797de2_0
  - glom=23.1.1=pyhd8ed1ab_0
  - gst-plugins-base=1.18.5=h9e645db_0
  - gstreamer=1.18.5=hd78058f_0
  - h5py=3.8.0=nompi_py310hae7a582_100
  - hdf4=4.2.15=h1b1b6ef_5
  - hdf5=1.12.2=nompi_h2a0e4a3_101
  - heapdict=1.0.1=pyhd3eb1b0_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=ha925a31_3
  - idna=3.4=py310haa95532_0
  - imagecodecs=2021.8.26=py310h6e7a67f_1
  - imageio=2.25.0=pyh24c5eb1_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib_resources=5.10.2=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=haa95532_3556
  - ipykernel=6.19.2=py310h9909e9c_0
  - ipynbname=2021.3.2=pyhd8ed1ab_0
  - ipython=8.8.0=py310haa95532_0
  - jasper=2.0.33=hc2e4405_1
  - jedi=0.18.1=py310haa95532_1
  - jinja2=3.1.2=py310haa95532_0
  - jpeg=9e=h2bbff1b_0
  - jsmin=3.0.1=pyhd8ed1ab_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=7.4.8=py310haa95532_0
  - jupyter_core=5.1.1=py310haa95532_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py310h232114e_1
  - lcms2=2.14=ha5c8aab_1
  - lerc=3.0=hd77b12b_0
  - libaec=1.0.6=h63175ca_1
  - libblas=3.9.0=1_h8933c1f_netlib
  - libbrotlicommon=1.0.9=hcfcfb64_8
  - libbrotlidec=1.0.9=hcfcfb64_8
  - libbrotlienc=1.0.9=hcfcfb64_8
  - libcblas=3.9.0=5_hd5c7e75_netlib
  - libclang=12.0.0=default_h627e005_2
  - libcurl=7.87.0=h86230a5_0
  - libdeflate=1.8=h2bbff1b_5
  - libffi=3.4.2=hd77b12b_6
  - libiconv=1.17=h8ffe710_0
  - liblapack=3.9.0=5_hd5c7e75_netlib
  - libnetcdf=4.8.1=nompi_h85765be_104
  - libogg=1.3.4=h8ffe710_1
  - libpng=1.6.39=h19919ed_0
  - libprotobuf=3.20.3=h23ce68f_0
  - libsodium=1.0.18=h62dcd97_0
  - libsqlite=3.40.0=hcfcfb64_0
  - libssh2=1.10.0=h680486a_2
  - libthrift=0.15.0=h636ae23_1
  - libtiff=4.5.0=h6c2663c_1
  - libvorbis=1.3.7=h0e60522_0
  - libwebp=1.2.4=h2bbff1b_0
  - libwebp-base=1.2.4=h2bbff1b_0
  - libxml2=2.9.14=h0ad7f3c_0
  - libxslt=1.1.35=h2bbff1b_0
  - libzip=1.9.2=hfed4ece_1
  - libzlib=1.2.13=hcfcfb64_4
  - libzopfli=1.0.3=h0e60522_0
  - locket=1.0.0=py310haa95532_0
  - lxml=4.9.1=py310h1985fb9_0
  - lz4=3.1.3=py310h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.1.1=py310h2bbff1b_0
  - matplotlib=3.6.3=py310h5588dad_0
  - matplotlib-base=3.6.3=py310h51140c5_0
  - matplotlib-inline=0.1.6=py310haa95532_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - micawber=0.5.4=pyhd8ed1ab_0
  - mistune=0.8.4=pyh1a96a4e_1006
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py310h2bbff1b_0
  - mkl_fft=1.3.1=py310ha0764ea_0
  - mkl_random=1.2.2=py310h4ed8f06_0
  - monotonic=1.5=py_0
  - msgpack-python=1.0.3=py310h59b6b97_0
  - msys2-conda-epoch=20160418=1
  - munch=2.5.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy=0.981=py310haa95532_0
  - mypy_extensions=0.4.3=py310haa95532_1
  - nbclient=0.5.13=pyhd8ed1ab_0
  - nbconvert=6.4.5=py310h5588dad_0
  - nbformat=5.7.3=pyhd8ed1ab_0
  - nest-asyncio=1.5.6=py310haa95532_0
  - netcdf4=1.6.2=py310hadf358c_0
  - networkx=3.0=pyhd8ed1ab_0
  - numexpr=2.8.4=py310hd213c9f_0
  - numpy=1.24.2=py310hd02465a_0
  - opencv=4.6.0=py310ha7641e4_2
  - openjpeg=2.5.0=ha2aaf27_2
  - openssl=1.1.1t=hcfcfb64_0
  - orderedmultidict=1.0.1=py_0
  - packaging=22.0=py310haa95532_0
  - pandas=1.5.2=py310h4ed8f06_0
  - pandoc=2.19.2=h57928b3_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pathspec=0.10.3=py310haa95532_0
  - pcre=8.45=h0e60522_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=22.3.1=py310haa95532_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.5.2=py310haa95532_0
  - ply=3.11=py_1
  - pooch=1.6.0=pyhd8ed1ab_0
  - posthog=2.2.0=pyhd8ed1ab_0
  - proj=9.1.1=heca977f_2
  - prompt-toolkit=3.0.36=py310haa95532_0
  - psutil=5.9.0=py310h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyarrow=8.0.0=py310h26aae1b_0
  - pycodestyle=2.10.0=py310haa95532_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=1.10.4=py310h8d17308_1
  - pydocstyle=6.3.0=py310haa95532_0
  - pyfftw=0.13.1=py310ha9ca8c9_0
  - pyflakes=3.0.1=py310haa95532_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pygrib=2.1.4=py310h3a12092_6
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyproj=3.4.1=py310hcdd211a_1
  - pyqt=5.15.7=py310hd77b12b_0
  - pyqt5-sip=12.11.0=py310hd77b12b_0
  - pyrsistent=0.19.3=py310h8d17308_0
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py310haa95532_0
  - pysteps=1.7.2=py310h8d17308_0
  - python=3.10.9=h966fe2a_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2022.7=py310haa95532_0
  - pywavelets=1.4.1=py310h9b08ddd_0
  - pywin32=305=py310h2bbff1b_0
  - pyyaml=6.0=py310h2bbff1b_1
  - pyzmq=23.2.0=py310hd77b12b_0
  - qt-main=5.15.2=he8e5bd7_7
  - qt-webengine=5.15.9=hb9a9bb5_5
  - qtwebkit=5.212=h3ad3cdb_4
  - re2=2022.04.01=h0e60522_0
  - requests=2.28.2=pyhd8ed1ab_0
  - requests-toolbelt=0.9.1=py_0
  - scikit-image=0.19.3=py310h1c4a608_2
  - scipy=1.10.0=py310h578b7cb_2
  - setuptools=65.6.3=py310haa95532_0
  - shapely=2.0.1=py310h8c82734_0
  - sip=6.6.2=py310h8a704f9_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=hfb803bf_2
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.40.1=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - stringcase=1.2.0=py_0
  - tabulate=0.8.10=pyhd8ed1ab_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - testpath=0.6.0=pyhd8ed1ab_0
  - tifffile=2021.4.8=pyhd8ed1ab_0
  - tk=8.6.12=h2bbff1b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py310haa95532_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - tornado=6.2=py310h2bbff1b_0
  - traitlets=5.7.1=py310haa95532_0
  - typing-extensions=4.4.0=py310haa95532_0
  - typing_extensions=4.4.0=py310haa95532_0
  - tzdata=2022g=h04d1e81_0
  - ucrt=10.0.20348.0=haa95532_0
  - unicodedata2=15.0.0=py310h8d17308_0
  - urllib3=1.26.14=py310haa95532_0
  - utf8proc=2.6.1=h2bbff1b_0
  - validators=0.18.2=pyhd3deb0d_0
  - vc=14.2=h21ff451_1
  - vega_datasets=0.9.0=pyhd3deb0d_0
  - vs2015_runtime=14.34.31931=h4c5c07a_10
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - wincertstore=0.2=py310haa95532_2
  - xz=5.2.10=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.4=hd77b12b_0
  - zfp=0.5.5=h0e60522_8
  - zict=2.1.0=py310haa95532_0
  - zipp=3.12.1=pyhd8ed1ab_0
  - zlib=1.2.13=hcfcfb64_4
  - zstd=1.5.2=h19a0ad4_0
  - pip:
      - astroid==2.15.0
      - dill==0.3.6
      - isort==5.12.0
      - lazy-object-proxy==1.9.0
      - loguru==0.6.0
      - opencv-python==4.7.0.68
      - pillow==9.4.0
      - tomlkit==0.11.6
      - win32-setctime==1.1.0
      - wrapt==1.15.0
prefix: C:\Users\davis.pazars\AppData\Local\miniconda3\envs\nwc
